package com.example.pluginbluetooth.bluetooth.gatt;

public enum GattConnectionAttempt {

    IDLE,
    WAITING_TO_START_CONNECTING,
    CONNECTING_ACTIVE,
    CONNECTING_ACTIVE_FAILED,
    CONNECTING_ACTIVE_SUCCESS,
    CONNECTING_ACTIVE_TIMED_OUT,
    CONNECTING_ACTIVE_TIMED_OUT_FORCED,
    CONNECTING_PASSIVE,
    CONNECTING_PASSIVE_SUCCESS,
    CONNECTING_PASSIVE_FAILED,
    CONNECTING_PASSIVE_TIMED_OUT
}
